[package]
name = "autostart"
edition.workspace = true
publish = false

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation = { workspace = true, features = ["objc2-core-services"] }
objc2-service-management = "0.3.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation", "Win32_Security", "Win32_System_Registry",
    "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging",
] }
